services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
  redis:
    image: redis:latest
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    depends_on:
      - redis


# # To start the service: 
# # $ docker compose -f .\docker-compose\dependency-docker-compose.yaml up -d

# # To down the service
# # $ docker compose -f .\docker-compose\dependency-docker-compose.yaml down