services:
  dataservice:
    image: dataservice
    volumes:
      - <full-path c:/...>/datasets:/data/
    ports:
      - 5000:5000
    networks: 
      data_net:
        ipv4_address: 172.26.0.2

  dataclient:
    image: dataclient
    depends_on: 
      - dataservice
    networks:
      data_net:
        ipv4_address: 172.26.0.3

networks:
  data_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.26.0.0/16"
    
# Be sure you are using the correct ip address in the app_test.sh file
# # You need to build the image dataservice and dataclient first
# # $ docker build -t dataservice .
# # $ docker build -t dataclient -f dataclient.dockerfile .

# # To start the service: 
# # $ docker compose up -d

# # To see output from the dataclient container.
# # $ docker compose logs dataclient

# # To down the service
# # $ docker compose down